/*
 * Copyright (C) 2025 Saien Naidu
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package FrontEnd;

// IMPORTS
import Managers.UniManager;
import Objects.Filter;
import javax.swing.JComboBox;

/**
 *
 * @author Saien Naidu
 */
public class FFilter extends javax.swing.JFrame {

    // FIELDS
    // University Manager
    private final UniManager um = new UniManager();

    // CONSTRUCTOR
    /**
     * Creates new form Filters
     */
    public FFilter() {
        initComponents();
        initComboBoxes();
    }

    // PROPERTIES
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnG = new javax.swing.ButtonGroup();
        pnl_filters = new javax.swing.JPanel();
        xbx_engineering = new javax.swing.JCheckBox();
        xbx_freestate = new javax.swing.JCheckBox();
        xbx_sciences = new javax.swing.JCheckBox();
        xbx_useMarks = new javax.swing.JCheckBox();
        btn_close = new javax.swing.JButton();
        rBtn_include = new javax.swing.JRadioButton();
        cbx_uni2 = new javax.swing.JComboBox<>();
        sep3 = new javax.swing.JSeparator();
        xbx_health = new javax.swing.JCheckBox();
        xbx_eastcape = new javax.swing.JCheckBox();
        cbx_uni3 = new javax.swing.JComboBox<>();
        cbx_uni1 = new javax.swing.JComboBox<>();
        xbx_commerce = new javax.swing.JCheckBox();
        xbx_kzn = new javax.swing.JCheckBox();
        sep2 = new javax.swing.JSeparator();
        xbx_limpopo = new javax.swing.JCheckBox();
        xbx_westcape = new javax.swing.JCheckBox();
        xbx_northwest = new javax.swing.JCheckBox();
        xbx_mpumalanga = new javax.swing.JCheckBox();
        rBtn_exclude = new javax.swing.JRadioButton();
        xbx_humanities = new javax.swing.JCheckBox();
        xbx_gauteng = new javax.swing.JCheckBox();
        sep1 = new javax.swing.JSeparator();
        xbx_law = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Filter");
        setAlwaysOnTop(true);
        setLocation(new java.awt.Point(570, 220));
        setName("Filters"); // NOI18N
        setResizable(false);
        setType(java.awt.Window.Type.POPUP);

        pnl_filters.setBackground(java.awt.SystemColor.menu);

        xbx_engineering.setForeground(new java.awt.Color(0, 0, 0));
        xbx_engineering.setText("Engineering");

        xbx_freestate.setForeground(new java.awt.Color(0, 0, 0));
        xbx_freestate.setText("Free State");

        xbx_sciences.setForeground(new java.awt.Color(0, 0, 0));
        xbx_sciences.setText("Sciences");

        xbx_useMarks.setForeground(new java.awt.Color(0, 0, 0));
        xbx_useMarks.setText("Use Your Marks");

        btn_close.setBackground(java.awt.SystemColor.menu);
        btn_close.setForeground(new java.awt.Color(0, 0, 0));
        btn_close.setText("[x]");
        btn_close.setBorder(null);
        btn_close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_closeActionPerformed(evt);
            }
        });

        btnG.add(rBtn_include);
        rBtn_include.setForeground(new java.awt.Color(0, 0, 0));
        rBtn_include.setText("Include these");

        xbx_health.setForeground(new java.awt.Color(0, 0, 0));
        xbx_health.setText("Health Sciences");

        xbx_eastcape.setForeground(new java.awt.Color(0, 0, 0));
        xbx_eastcape.setText("East Cape");

        xbx_commerce.setForeground(new java.awt.Color(0, 0, 0));
        xbx_commerce.setText("Commerce");

        xbx_kzn.setForeground(new java.awt.Color(0, 0, 0));
        xbx_kzn.setText("KZN");

        xbx_limpopo.setForeground(new java.awt.Color(0, 0, 0));
        xbx_limpopo.setText("Limpopo");

        xbx_westcape.setForeground(new java.awt.Color(0, 0, 0));
        xbx_westcape.setText("West Cape");

        xbx_northwest.setForeground(new java.awt.Color(0, 0, 0));
        xbx_northwest.setText("North West");

        xbx_mpumalanga.setForeground(new java.awt.Color(0, 0, 0));
        xbx_mpumalanga.setText("Mpumalanga");

        btnG.add(rBtn_exclude);
        rBtn_exclude.setForeground(new java.awt.Color(0, 0, 0));
        rBtn_exclude.setText("Exclude these");

        xbx_humanities.setForeground(new java.awt.Color(0, 0, 0));
        xbx_humanities.setText("Humanities");

        xbx_gauteng.setForeground(new java.awt.Color(0, 0, 0));
        xbx_gauteng.setText("Gauteng");
        xbx_gauteng.setToolTipText("");

        xbx_law.setForeground(new java.awt.Color(0, 0, 0));
        xbx_law.setText("Law");

        javax.swing.GroupLayout pnl_filtersLayout = new javax.swing.GroupLayout(pnl_filters);
        pnl_filters.setLayout(pnl_filtersLayout);
        pnl_filtersLayout.setHorizontalGroup(
            pnl_filtersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sep1)
            .addComponent(sep2)
            .addComponent(sep3)
            .addGroup(pnl_filtersLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_filtersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_filtersLayout.createSequentialGroup()
                        .addGroup(pnl_filtersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnl_filtersLayout.createSequentialGroup()
                                .addComponent(xbx_useMarks)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btn_close, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnl_filtersLayout.createSequentialGroup()
                                .addComponent(xbx_kzn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(xbx_gauteng)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(xbx_eastcape)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(xbx_westcape)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(pnl_filtersLayout.createSequentialGroup()
                        .addGroup(pnl_filtersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnl_filtersLayout.createSequentialGroup()
                                .addComponent(xbx_freestate)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(xbx_northwest)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(xbx_mpumalanga)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(xbx_limpopo))
                            .addGroup(pnl_filtersLayout.createSequentialGroup()
                                .addComponent(xbx_commerce)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(xbx_engineering)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(xbx_health)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(xbx_law))
                            .addGroup(pnl_filtersLayout.createSequentialGroup()
                                .addComponent(xbx_humanities)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(xbx_sciences)))
                        .addGap(0, 53, Short.MAX_VALUE))
                    .addGroup(pnl_filtersLayout.createSequentialGroup()
                        .addGroup(pnl_filtersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(cbx_uni3, javax.swing.GroupLayout.Alignment.LEADING, 0, 250, Short.MAX_VALUE)
                            .addComponent(cbx_uni2, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cbx_uni1, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(pnl_filtersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rBtn_include, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rBtn_exclude, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20))))
        );
        pnl_filtersLayout.setVerticalGroup(
            pnl_filtersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_filtersLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_filtersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(xbx_useMarks)
                    .addComponent(btn_close))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sep1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnl_filtersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(xbx_kzn)
                    .addComponent(xbx_gauteng)
                    .addComponent(xbx_eastcape)
                    .addComponent(xbx_westcape))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnl_filtersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(xbx_freestate)
                    .addComponent(xbx_northwest)
                    .addComponent(xbx_mpumalanga)
                    .addComponent(xbx_limpopo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(sep2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnl_filtersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(xbx_commerce)
                    .addComponent(xbx_engineering)
                    .addComponent(xbx_health)
                    .addComponent(xbx_law))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnl_filtersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(xbx_humanities)
                    .addComponent(xbx_sciences))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnl_filtersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnl_filtersLayout.createSequentialGroup()
                        .addComponent(sep3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbx_uni1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbx_uni2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbx_uni3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(26, Short.MAX_VALUE))
                    .addGroup(pnl_filtersLayout.createSequentialGroup()
                        .addComponent(rBtn_include)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rBtn_exclude)
                        .addGap(34, 34, 34))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl_filters, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl_filters, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // <editor-fold defaultstate="collapsed" desc="Initialization code">
    // Creates and sets the models of the combo boxes
    private void initComboBoxes() {
        JComboBox uni1 = new JComboBox(um.getAll());
        cbx_uni1.setModel(uni1.getModel());
        JComboBox uni2 = new JComboBox(um.getAll());
        cbx_uni2.setModel(uni2.getModel());
        JComboBox uni3 = new JComboBox(um.getAll());
        cbx_uni3.setModel(uni3.getModel());
    }
    // </editor-fold>

    // When [x] is clicked, send filter to main
    private void btn_closeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_closeActionPerformed

        // Use user marks?
        boolean useMarks = xbx_useMarks.isSelected();

        // Use location of?
        boolean kzn = xbx_kzn.isSelected();
        boolean gauteng = xbx_gauteng.isSelected();
        boolean eastcape = xbx_eastcape.isSelected();
        boolean westcape = xbx_westcape.isSelected();
        boolean freestate = xbx_freestate.isSelected();
        boolean northwest = xbx_northwest.isSelected();
        boolean mpumalanga = xbx_mpumalanga.isSelected();
        boolean limpopo = xbx_limpopo.isSelected();

        // Use faculty of?
        boolean commerce = xbx_commerce.isSelected();
        boolean engineering = xbx_engineering.isSelected();
        boolean health = xbx_health.isSelected();
        boolean law = xbx_law.isSelected();
        boolean humanities = xbx_humanities.isSelected();
        boolean sciences = xbx_sciences.isSelected();

        // Use university of?
        String uni1 = (String) cbx_uni1.getSelectedItem();
        String uni2 = (String) cbx_uni2.getSelectedItem();
        String uni3 = (String) cbx_uni3.getSelectedItem();

        // Include or exclude the selected universities
        // Only one of the two can be true, but both can be false
        boolean include;
        boolean exclude;

        // If no university selected:
        if ((uni1.equals("None"))
                && (uni2.equals("None"))
                && (uni3.equals("None"))) {
            // Set both to false
            include = false;
            exclude = false;
        } else { // Otherwise:
            // Set either as true based on user selection
            include = rBtn_include.isSelected();
            exclude = rBtn_exclude.isSelected();
        }

        // Create the filter object
        Filter filter = new Filter(useMarks, kzn, gauteng, eastcape, westcape, freestate, northwest, mpumalanga, limpopo, commerce, engineering, health, law, humanities, sciences, uni1, uni2, uni3, include, exclude);

        // Deactivate this frame
        this.setVisible(false);
        this.setEnabled(false);

        // Show main frame and send trigger
        FMain frm_main = new FMain();
        frm_main.updateFinderTable(filter);
        frm_main.setVisible(true);
    }//GEN-LAST:event_btn_closeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FFilter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new FFilter().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btnG;
    private javax.swing.JButton btn_close;
    private javax.swing.JComboBox<String> cbx_uni1;
    private javax.swing.JComboBox<String> cbx_uni2;
    private javax.swing.JComboBox<String> cbx_uni3;
    private javax.swing.JPanel pnl_filters;
    private javax.swing.JRadioButton rBtn_exclude;
    private javax.swing.JRadioButton rBtn_include;
    private javax.swing.JSeparator sep1;
    private javax.swing.JSeparator sep2;
    private javax.swing.JSeparator sep3;
    private javax.swing.JCheckBox xbx_commerce;
    private javax.swing.JCheckBox xbx_eastcape;
    private javax.swing.JCheckBox xbx_engineering;
    private javax.swing.JCheckBox xbx_freestate;
    private javax.swing.JCheckBox xbx_gauteng;
    private javax.swing.JCheckBox xbx_health;
    private javax.swing.JCheckBox xbx_humanities;
    private javax.swing.JCheckBox xbx_kzn;
    private javax.swing.JCheckBox xbx_law;
    private javax.swing.JCheckBox xbx_limpopo;
    private javax.swing.JCheckBox xbx_mpumalanga;
    private javax.swing.JCheckBox xbx_northwest;
    private javax.swing.JCheckBox xbx_sciences;
    private javax.swing.JCheckBox xbx_useMarks;
    private javax.swing.JCheckBox xbx_westcape;
    // End of variables declaration//GEN-END:variables
}
